name: test workflow

on: push

jobs:
  name: playin
     test:
       runs-on: ubuntu-latest
       steps:
             name: checkout phase
             uses: actions/checkout@v3
             run: |
              mkdir bb
              new-item "making-cash.txt"
              echo "Devops Eng" > making-cash.txt